pipeline {
    agent any
    tools {
        ant "$(brew --prefix ant)"
    }
    stages {
        stage('Clean') 
        {
            steps 
            {
                sh "ant clean"
            }
        }
        stage('Build') 
        {
            steps 
            {
                sh "ant build"
            }
        }
        stage('Test') 
        {
            steps 
            {
                sh "ant AdditionTest"
            }
        }
        stage('Mutation_Testing') 
        {
            steps 
            {
                sh "ant pit"
            }
        }
        stage('Find_Bugs') 
        {
            steps 
            {
                sh "ant spotbugs"
            }
        }
    }
}
